# Generated by Django 5.1.7 on 2025-03-15 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_question', models.CharField(max_length=100)),
                ('text', models.TextField(default=':( برای این روز هنوز متنی نوشته نشده است')),
                ('secret_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateField(default=datetime.date.today, unique=True)),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
