# Generated by Django 5.1.7 on 2025-03-16 20:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_question', models.CharField(max_length=100)),
                ('text', models.TextField(default=':( برای این روز هنوز متنی نوشته نشده است')),
                ('secret_text', models.TextField(blank=1, null=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateField(default=datetime.date.today, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('keywords', models.TextField(blank=1, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_bar_title', models.CharField(max_length=100)),
                ('page_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
