# Generated by Django 5.1.7 on 2025-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='is_active',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
