# Generated by Django 5.1.7 on 2025-03-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_is_developer_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='secret_text',
            field=models.TextField(blank=1, null=1),
        ),
    ]
