# Generated by Django 5.1.7 on 2025-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_secret_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=1, null=1),
            preserve_default=1,
        ),
    ]
