# Generated by Django 5.1.7 on 2025-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogsettings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
