# Generated by Django 5.1.7 on 2025-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogsettings_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettings',
            name='title',
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='page_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='tab_bar_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
