# Generated by Django 5.1.7 on 2025-03-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='MyCustomUser',
        ),
    ]
