# Generated by Django 5.1.7 on 2025-03-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_rename_customuser_mycustomuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCustomUser',
            new_name='CustomUser',
        ),
    ]
