# Generated by Django 5.1.7 on 2025-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name_in_persian',
            field=models.CharField(blank=1, max_length=50, null=1),
            preserve_default=1,
        ),
    ]
