# Generated by Django 5.1.7 on 2025-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_customuser_full_name_in_persian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name_in_persian',
            new_name='first_name_in_persian',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_in_persian',
            field=models.CharField(blank=1, max_length=50, null=1),
            preserve_default=1,
        ),
    ]
