# Generated by Django 5.1.7 on 2025-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_rename_full_name_in_persian_customuser_first_name_in_persian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
