# Generated by Django 5.1.7 on 2025-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
